sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: X9hBR3K0OirRFbkOGqFfIlLFzFBXykUHHdCdXFvlVqukY659BnHqC9rAA6DrLHhzAhF11OvEx5+hOeQ+nKRaSoBDWQUp4wwAZw5y1KnBgd1teTcPl3v8IPiHQIxLaQSqGdjY3Gnz1NbY49uE3wa1x34bhqqnvayBUCpaz4hGaK3AOj7ICmUfeTvcBFCLKsb+HakGdbRf3qblcL2BjGoYJWeCfRRF7Goc1KqZb0dQ9Q2lvmR5e802WuhFmiKpoovCYt7Ux2qN+42mnwN2CKLkI+ztopXW+79O4pxpdMQ9PS4nw2l68fSjLtT1uUX/7cDnYhtf69AE4FBib0tJ8HQ9Vt7yz9okcH2R+VB0wX+N86BFCYnevjf9RHgYV/0nANpwZPflYcI0QkivwPOEXPS5+BnQJx6i6NzIH1WnHnj79FbnOyeXg/BdFXNwMT6gpcJUfV+4zkkukwo3eBJHOfUXa/OrjS7QEVXNh7PiHG2H954/guACIMUGOiZeEyeklh+nw5V1t8OYlpcifc8/Jqz5rSYvgwfZwfJrkB8HKhoAgBroQ5sxkdFpgnde+kkZJFwjDngCEYDtI8DG45fhhlM1LJsNz+sqfbod/wxL2lacqlN0p0hJYBhgtuDDPRZAVjGya+1JkjQJWUxuMFquQBWcpFH2h/ARuv2Vx/a+6FyJ5T4=
before_install:
- git clone http://github.com/dock0/pkgforge-golang-cross
- docker build -t dock0/pkgforge-golang-cross pkgforge-golang-cross
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: GBM5QrPMovWxTJii/QW4tzEjP8Op4QsNZzynkemA7W7QR6pzQ3Iy7aR7i1pGJjEvbFAGQewb5VfJtXRzHR4+58snDTh6O7hM89rtnP3cifBA/X//jttdjrjoJpaUBGUCSPLtEX6ayldcvKX89iLT3K2zzj67m1HfBs3CXDjA0XvcUI6pVjukEdHxEPe1JHiKvQCarCA3Ir31mCN98bUhVCmYc5BeTVlvAoidMALzG52htkG0tp47m8EGUV7c8XlF4X5rY9rjZ4La6lUpBW/6HvlkOkxHWC9URbKVffQ1q6ejJspSKP7g1v8u2qMrWGV5K1LlsHAdCBv3d1Ac3rzeiqMkMS2ue4CnnzsBu7ednRYQBd0T28dKU+yzN817Vzf92c/mQ/Jz6+LQpNvx7J6o/cyzFduCsbGOtoudc6yDZXVMBFc9Eln3YmFPPo7n3AOLFsUovITgLbqhgjnz7gPxeXr9U4YQpJ8JTuxHl8/7s0ACNEZvWYi9A14HrYwo+U7HiSGBi5F+Xiy96D3LdJ5IF2s60jcF8P6x1N94fof5paK/jg6vVlJD0wc2f/U2ELD27slklzoYjHDYZGB4H81KOmE+V5r8i39wNZc0oQQ6UQ0953b3p/WD/ZvAvDJpML+sLJYv44ZzmbDPOk/whtKFtlDBo6HHzfix8Wy7QiCGhw8=
